// Mocks generated by Mockito 5.4.6 from annotations
// in accessa_mobile/test/ui/devices/view_model/device_detail_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:accessa_mobile/data/services/mqtt_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mqtt_client/mqtt_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MqttService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMqttService extends _i1.Mock implements _i2.MqttService {
  MockMqttService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.MqttReceivedMessage<_i4.MqttMessage>> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue:
                _i3.Stream<_i4.MqttReceivedMessage<_i4.MqttMessage>>.empty(),
          )
          as _i3.Stream<_i4.MqttReceivedMessage<_i4.MqttMessage>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> subscribe(
    String? topic, {
    _i4.MqttQos? qos = _i4.MqttQos.atLeastOnce,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic], {#qos: qos}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> publishString(
    String? topic,
    String? payload, {
    _i4.MqttQos? qos = _i4.MqttQos.atLeastOnce,
    bool? retain = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishString,
              [topic, payload],
              {#qos: qos, #retain: retain},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
