name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - feat/tela-inicial
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build (Web)
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Altere o --base-href se for usar domínio personalizado/CNAME
          flutter build web --release --base-href="/${REPO_NAME}/"
          # Copia index para 404 para SPA routing opcional
          cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true
